permalink: /:title/
title: 'Hazelmead Community Energy'

google_analytics_id: "G-BZ0JNJMGT6"

homepage:
  show_call_box: true

logo:
  main: "assets/images/logo.png"
  light: "assets/images/logo-light.png"

esco:
  name: Hazelmead
  domain: hazelmead.energy
  email: hello@hazelmead.energy
  phone: "+44 330 828 3096"
  app_url: https://app.hazelmead.energy"
  description: "Bridport Cohousing, Clean Energy Prospector, and Bristol Energy Co-operative have partnered to design a microgrid at the Hazlemead housing development that is redeﬁning the way housing estates provide an energy service to its residents."

seo:
  meta_og_title: "Hazelmead Community Energy"
  meta_og_type: "website"
  meta_og_url: "https://cepro.github.io/www.hazelmead.energy-jekyll/"
  meta_og_image: "https://cepro.github.io/www.hazelmead.energy-jekyll/assets/images/cepro-illa-water-lillies-2.webp"
  meta_og_description: {{ site.esco.description }}
  meta_og_keywords: "The Hazelmead Community Energy company has been created to provide you with: Cheaper bills, Lower carbon footprint, Simple pricing and flat rate tariff, Integrated EV charging, Smart Heat"
  meta_twitter_card: "summary"
  meta_twitter_site: "@mappix"
  meta_twitter_creator: "@mappix"

collections:
  category:
    output: false

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-environment-variables

gems: ['kramdown']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - vendor
  - Procfile
  - Rakefile

# for local run
url: http://0.0.0.0:4000
baseurl: ''
host: 0.0.0.0
