permalink: /:title/
title: 'Water Lilies Community Energy'

google_analytics_id: "G-DTPQPFRN9Z"

homepage:
  show_call_box: true

logo:
  main: "assets/images/logo.png"
  light: "assets/images/logo-light.png"

footer:
  copyright_text: 'You can start and finish one of these popular software landing in under a day - for free! Check the list below'

seo:
  meta_og_title: "Water Lilies Community Energy"
  meta_og_type: "website"
  meta_og_url: "https://cepro.github.io/www.waterlilies.energy-jekyll/"
  meta_og_image: "https://cepro.github.io/www.waterlilies.energy-jekyll/assets/images/cepro-illa-water-lillies-2.webp"
  meta_og_description: "Bright Green Futures, Clean Energy Prospector, and Bristol Energy Co-operative have partnered to design a microgrid at the Water Lilies housing development in Kingsweston, Bristol that is redeﬁning the way housing estates provide an energy service to its residents."
  meta_og_keywords: "The Water Lilies Community Energy company has been created to provide you with: Cheaper bills, Lower carbon footprint, Simple pricing and flat rate tariff, Integrated EV charging, Smart Heat"
  meta_twitter_card: "summary"
  meta_twitter_site: "@mappix"
  meta_twitter_creator: "@mappix"

collections:
  category:
    output: false

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-environment-variables

gems: ['kramdown']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - vendor
  - Procfile
  - Rakefile

# for local run
url: http://0.0.0.0:4000
baseurl: ''
host: 0.0.0.0
