# for github pages setup uncomment the code and set to your domain
# domain: yourdomain.com      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cepro.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: 'www.waterlilies.energy-jekyll'       # place folder name if the site is served in a subfolder   
host: cepro.github.io