baseurl: ''
permalink: /:title/
title: 'Water Lilies Community Energy'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  main: "assets/images/logo.png"
  light: "assets/images/logo-light.png"

footer:
  copyright_text: 'You can start and finish one of these popular software landing in under a day - for free! Check the list below'

seo:
  meta_og_title: "Water Lilies Community Energy"
  meta_og_type: "website"
  meta_og_url: "https://themeplugs.com"
  meta_og_image: "g"
  meta_og_description: "Water Lilies Energy"
  meta_og_keywords: "The Water Lilies Community Energy company has been created to provide you with: Cheaper bills, Lower carbon footprint, Simple pricing and flat rate tariff, Integrated EV charging, Smart Heat"
  meta_twitter_card: "summary"
  meta_twitter_site: "@mappix"
  meta_twitter_creator: "@mappix"

collections:
  category:
    output: false

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10
  sass_dir: _sass

plugins:
  - jekyll-environment-variables

gems: ['kramdown']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - vendor
  - Procfile
  - Rakefile

# for github pages setup uncomment the code and set to your domain
# domain: yourdomain.com      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cepro.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: 'www.waterlilies.energy-jekyll'       # place folder name if the site is served in a subfolder   